### ISSUE TITLE
feat: detect user language and set as default if exists

### ISSUE THREAD

**Issue by hu8813** [reunu/unustasis#73]
for a better user experience, having the default language same as the device langauge (Localizations.localeOf(context).languageCode) would be nice without need of setting it manually

i.e. if phone language is German, on the first usage app can set German as default language instead of English, so that user does not need 3x click / search where to set language.

**Comment by TheFreal** [comment]
Ideally, that is how it should work. However it seems there is currently a bug in the system language recognition, I'll look into it.
