### ISSUE TITLE
Privacy Policy (Datenschutzerklärung) could be improved

### ISSUE THREAD

**Issue by hu8813** [reunu/unustasis#74]
hi. thanks for the 1.2.2 update.
the Privacy Policy at Play store page (a .txt file on github gist) could be improved
- not the same url as the Policy inside the App (unu domain)
- not good readable on mobile phone when clicked on play store
- does not explain for what Gps is used, although Gps Authorization is needed

inside the App, the privacy policy is not viewable without Pairing a scooter with app

it's not uncommon that Google/Apple later finds out that something is missing and forces to update the App. For that reason would be better to improve the privacy policy.

**Comment by TheFreal** [comment]
Good point, thanks for noticing! I've replaced the privacy policy URL on Google Play to match the one of the official Unu app.
