### ISSUE TITLE
Sync clock with App

### ISSUE THREAD

**Issue by t-knapp** [reunu/unustasis#76]
Hello,

I found this awesome project and want to thank you guys! The app literally made my day. My scooters eSIM seems to be blocked / deactivated and I can't connect the official unu app.

The scooters clock is off by hours and is not synced due to missing network connection.

Is it possible to set the scooters clock via any BLE characteristics?

Kind regards,
Tobias

**Comment by TheFreal** [comment]
Unfortunately, the scooter offers no BLE characteristic for setting the clock, and won't without a firmware update. So for the time being, there is no way to fix the clock via the app.
