### ISSUE TITLE
setting from Park to Standby mode when seatbox is open

### ISSUE THREAD

**Issue by hu8813** [reunu/unustasis#79]
Issue: No Alert When Switching to Standby with Open Seatbox
Description
When the seatbox is open and the user attempts to switch from Park to Standby mode, there is no alert in the app indicating that the seatbox is open. This can lead to confusion, making users think the system is frozen or malfunctioning.

Expected Behavior
An alert should appear stating, "Seatbox is open. Please close the seatbox to switch to Standby mode."

Impact
The lack of notification has caused confusion multiple times regarding the vehicle's status.

**Comment by TheFreal** [comment]
God damn it, there definitely should be a warning, and I spent days fixing it when it broke just a few months ago. No clue why it's broken again now, I'll look into it. Thanks for bringing it to my attention!
